services:
    Sandronimus\NelmioFormGetParameterPluginBundle\Services\FormGetParameterRouteDescriber:
        arguments:
            $formFactory: '@form.factory'
        tags:
            - 'nelmio_api_doc.route_describer'
